class_name: "ddxdriver.ddxdrivers.open_choice.OpenChoice"
config:
  agent_prompt_length: 10                  # 0 if no instructions, otherwise a positive number
  available_agents: ["history_taking", "rag", "diagnosis"]  #List subset of ["history_taking", "rag", "diagnosis"], this is used for the order
  max_turns: 6

  model:
    class_name: ddxdriver.models.oai_chat.OpenAIChat  #["oai_azure_chat.OpenAIAzureChat", "oai_chat.OpenAIChat", "llama3_instruct.Llama3Instruct", "llama31_8b.Llama318B"]
    config:
      model_name: "gpt-4o"  # ["gpt-4o", "llama31instruct", "meta-llama/Meta-Llama-3.1-8B-Instruct"]
